config/routes.rb
Rails.application.routes.draw do 
  
  root 'people#index'

  get '/about', to: 'people#about'
  
  resources :people
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all.order(:last_name)
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(people_params)
 
    if @person.save
      redirect_to people_path
    else
      render :new
    end
  end
 
  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
  
    if @person.update(people_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to people_path
  end

  private
 
    def people_params
      params.require(:person).permit(:first_name, :last_name, :age, :hair_color, :eye_color, :gender, :alive)
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'People', people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeopleProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
</body>
</html>

app/views/people/edit.html.erb
<h1>Edit Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <br/>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <br/>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <br/>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <br/>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <br/>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <br/>

  <%= f.label :alive %>
  <%= f.check_box :alive %>

  <br/>

  <%= f.submit %>
<% end %>

app/views/people/index.html.erb
<h1> People </h1>
<p><%= link_to 'Add', new_person_path %></p>
<% @people.each do |person| %>
  <h2><%= person.first_name %></h2>
  <%= link_to "Info", person_path(person) %>
  <br/>
  <%= link_to "Edit", edit_person_path(person) %>
  <br/>
  <%= link_to 'Remove', person, method: :delete %>
<% end %>

app/views/people/new.html.erb
<h1>Add a New Person</h1>
<%= form_for @person do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>

  <br/>

  <%= f.label :last_name %>
  <%= f.text_field :last_name %>

  <br/>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <br/>

  <%= f.label :hair_color %>
  <%= f.text_field :hair_color %>

  <br/>

  <%= f.label :eye_color %>
  <%= f.text_field :eye_color %>

  <br/>

  <%= f.label :gender %>
  <%= f.text_field :gender %>

  <br/>

  <%= f.label :alive %>
  <%= f.check_box :alive %>

  <br/>

  <%= f.submit %>
<% end %>

app/views/people/show.html.erb
<h1>First Name: <%= @person.first_name %></h1>
<h1>Last Name: <%= @person.last_name %></h1>
<h1>Age: <%= @person.age %></h1>
<h1>Hair Color: <%= @person.hair_color %></h1>
<h1>Eye Color: <%= @person.eye_color %></h1>
<h1>Gender: <%= @person.gender %></h1>
<h1>Alive? <% if @person.alive == true %>
  <%= "Still kicking" %>
<% else %>
  <%= "Rest in peace" %>
<% end %></h1>

<%= link_to 'Back', people_path %>s